# Generated by Django 5.1.3 on 2024-12-25 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_application', models.DateField()),
                ('status', models.CharField(choices=[('WAITING', 'waiting'), ('APPROVED', 'approved'), ('DECLINED', 'declined')], max_length=15)),
                ('adress', models.CharField(max_length=50)),
                ('pod', models.CharField(max_length=50)),
                ('kvar', models.CharField(max_length=50)),
                ('phnumber', models.CharField(max_length=15)),
                ('price_status', models.CharField(choices=[('PAID', 'paid'), ('UNPAID', 'unpaid')], max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarif', to=settings.AUTH_USER_MODEL)),
                ('tarif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarif', to='tariff.tariff')),
            ],
        ),
    ]
